server:
  port: 9000

swagger:
  enable: true

spring:
  datasource:
    dynamic:
      datasource:
        # 读数据库
        master:
          url: jdbc:mysql://39.105.30.146:3306/appweb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 500000
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志