server:
  port: 9000

swagger:
  enable: true

spring:
  datasource:
    dynamic:
      datasource:
        # 读数据库
        master:
          url: jdbc:mysql://47.92.212.63:3306/appweb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: root
          password: bjfu1022
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 500000
  thymeleaf:
    cache: false
minio:
  endpoint: http://47.105.176.145:8082/
  accesskey: adminkey
  ascretkey: adminpass
mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志