package com.ctsi.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;

import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * @author ctsi-biyi-generator
*/
public class TbActive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.name
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.desc
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.cost
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private Float cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.address
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.create_user_id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.code
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.images
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.start_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private ZonedDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.end_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private ZonedDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.mobile
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_active.person_num
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    private Integer personNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.id
     *
     * @return the value of tb_active.id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.id
     *
     * @param id the value for tb_active.id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.name
     *
     * @return the value of tb_active.name
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.name
     *
     * @param name the value for tb_active.name
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.desc
     *
     * @return the value of tb_active.desc
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.desc
     *
     * @param desc the value for tb_active.desc
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.cost
     *
     * @return the value of tb_active.cost
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.cost
     *
     * @param cost the value for tb_active.cost
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.address
     *
     * @return the value of tb_active.address
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.address
     *
     * @param address the value for tb_active.address
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.create_user_id
     *
     * @return the value of tb_active.create_user_id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.create_user_id
     *
     * @param createUserId the value for tb_active.create_user_id
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.code
     *
     * @return the value of tb_active.code
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.code
     *
     * @param code the value for tb_active.code
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.images
     *
     * @return the value of tb_active.images
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.images
     *
     * @param images the value for tb_active.images
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.start_time
     *
     * @return the value of tb_active.start_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public ZonedDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.start_time
     *
     * @param startTime the value for tb_active.start_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setStartTime(ZonedDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.end_time
     *
     * @return the value of tb_active.end_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public ZonedDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.end_time
     *
     * @param endTime the value for tb_active.end_time
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setEndTime(ZonedDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.mobile
     *
     * @return the value of tb_active.mobile
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.mobile
     *
     * @param mobile the value for tb_active.mobile
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_active.person_num
     *
     * @return the value of tb_active.person_num
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public Integer getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_active.person_num
     *
     * @param personNum the value for tb_active.person_num
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_active
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbActive other = (TbActive) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getCost() == null ? other.getCost() == null : this.getCost().equals(other.getCost()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getImages() == null ? other.getImages() == null : this.getImages().equals(other.getImages()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getPersonNum() == null ? other.getPersonNum() == null : this.getPersonNum().equals(other.getPersonNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_active
     *
     * @mbg.generated Wed Dec 09 15:28:43 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getCost() == null) ? 0 : getCost().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getImages() == null) ? 0 : getImages().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getPersonNum() == null) ? 0 : getPersonNum().hashCode());
        return result;
    }
}