package com.ctsi.entity;

import java.io.Serializable;

/**
 * @author ctsi-biyi-generator
*/
public class TbMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.id
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.name
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.code
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.url
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.component
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.method
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.parentid
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.id
     *
     * @return the value of tb_menu.id
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.id
     *
     * @param id the value for tb_menu.id
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.name
     *
     * @return the value of tb_menu.name
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.name
     *
     * @param name the value for tb_menu.name
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.code
     *
     * @return the value of tb_menu.code
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.code
     *
     * @param code the value for tb_menu.code
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.url
     *
     * @return the value of tb_menu.url
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.url
     *
     * @param url the value for tb_menu.url
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.component
     *
     * @return the value of tb_menu.component
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.component
     *
     * @param component the value for tb_menu.component
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.method
     *
     * @return the value of tb_menu.method
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.method
     *
     * @param method the value for tb_menu.method
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.parentid
     *
     * @return the value of tb_menu.parentid
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.parentid
     *
     * @param parentid the value for tb_menu.parentid
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbMenu other = (TbMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getComponent() == null ? other.getComponent() == null : this.getComponent().equals(other.getComponent()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbg.generated Wed Dec 09 15:32:33 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getComponent() == null) ? 0 : getComponent().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        return result;
    }
}